package br.com.souza.saga_orchestrator.application.domain.model

enum class SagaStep {
    ORDER_CREATED,
    RESERVING_STOCK_PENDING,
    RESERVING_STOCK_COMPLETED,
    RESERVING_STOCK_FAILED,
    PROCESSING_PAYMENT_PENDING,
    PROCESSING_PAYMENT_COMPLETED,
    PROCESSING_PAYMENT_FAILED,
    CONFIRMING_ORDER_PENDING,
    CONFIRMING_ORDER_COMPLETED,
    CONFIRMING_RESERVATION_PENDING,
    CONFIRMING_RESERVATION_COMPLETED,
    RELEASING_STOCK_PENDING,
    RELEASING_STOCK_COMPLETED,
    CANCELING_ORDER_PENDING,
    CANCELING_ORDER_COMPLETED,
    ORDER_COMPLETED,
    ORDER_FAILED
}
