name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      orders: ${{ steps.changes.outputs.orders }}
      payments: ${{ steps.changes.outputs.payments }}
      inventory: ${{ steps.changes.outputs.inventory }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            orders:
              - 'orders-service/**'
            payments:
              - 'payments-service/**'
            inventory:
              - 'inventory-service/**'

  build-orders:
    needs: detect-changes
    if: needs.detect-changes.outputs.orders == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./orders-service
          push: true
          tags: vsouzx/orders-service:latest

  build-payments:
    needs: detect-changes
    if: needs.detect-changes.outputs.payments == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./payments-service
          push: true
          tags: vsouzx/payments-service:latest

  build-inventory:
    needs: detect-changes
    if: needs.detect-changes.outputs.inventory == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./inventory-service
          push: true
          tags: vsouzx/inventory-service:latest
